schema_version = "1.0.0"

id = "armature_tools"
version = "1.0.0"
name = "Armature Tools"
tagline = "Tools for working with armatures: B-Bone display, bone scaling, camera follow, and frame range"
maintainer = "Developer"
type = "add-on"

tags = ["Animation", "Rigging"]

blender_version_min = "5.0.0"

license = [
  "SPDX:GPL-3.0-or-later",
]
